# Site settings
title: "江の島エンジニアBlog"
description: "湘南在住, 渋谷で働くエンジニアのブログです"
profile: "湘南から渋谷に通うエンジニアです。お祝い金がもらえる賃貸情報サイト <a href=\"http://cbchintai.com\">キャッシュバック賃貸</a>の開発をしています。<br/>以前はTwitter全量リアルタイム解析サービス <a href=\"https://www.nttcoms.com/service/buzzfinder/\">BuzzFinder</a> の設計・開発をしていました。<br/>技術分野はRuby/Railsベースのアジャイル開発、Hadoopでの大規模分散処理など。"
baseurl: ""
domain: blog.enogineer.com
url: "http://blog.enogineer.com"
author_image: https://s.gravatar.com/avatar/f3cde9d5daed8b98e02dfd2d6a1d6355?s=72
twitter_username: haracane
#twitter_username_ruby: はらけん
github_username:  haracane
#qiita_username:  haracane
google_analysis_id: UA-53664731-1
amazon_associate_id: haracane-22
paginate: 10

post_summary_sidebar: true
footer_tags: true

keywords: "江の島"

h1:
  index: "Ruby(Rails, RSpec)やHadoop, Elasticsearchでのデータ処理などについてよく書いています"
  genre: "各タグに関連する記事の一覧です:"
  backnumber: 過去に投稿した記事の一覧です

# 320, 240, 120
# for file in $(ls); do ruby -e 'readlines.each_with_index { |line, i| if i > 0 && line == "---\n" then print "image: blank.gif\n"; end;  print line }' -i $file; done
styles:
  post:
    image_class: w0
  summary:
    image_class: w60
  index:
    layout: post/default-summary.html
    wrap_class: ""
    layout_center_class: layout-center
    box_class: ""
    sidebar: true
  backnumber:
    layout: post/description-link.html
    wrap_class: ""
    layout_center_class: layout-center
    box_class: "border-box padding-box"
    sidebar: true
  nav-post-link:
    layout: post/text-link.html
  tag-post-link:
    layout: post/description-link.html
  category-post-link:
    layout: post/category-text-link.html

category_navigations:
  -
    name: トップ
    url: /
  -
    name: ジャンル
    url: /genre/dp.html
  -
    name: バックナンバー
    url: /backnumber.html

link_boxes:
  -
    title: 関連コンテンツ
    type: dl
    links:
      -
        title: Qiita:haracane
        description: 技術メモの更新のサマリをお知らせしています
        url: http://qiita.com/haracane
      -
        title: 業務スーパーかんたんレシピ
        description: おすすめ料理レシピを投稿しています
        url: http://gsrecipe.com
      -
        title: 始発駅.com
        description: 始発駅の時刻表をまとめています
        url: http://shihatsueki.com
      -
        title: haracaneのはてなブログ
        description: ブログの更新をまとめてお知らせしています
        url: http://haracane.hateblo.jp

  -
    title: リンク
    links:
      -
        title: Github:haracane
        url: https://github.com/haracane
      -
        title: Rubygems:haracane
        url: https://rubygems.org/profiles/58011
      -
        title: SlideShare:haracane
        url: http://www.slideshare.net/haracane
      -
        title: LinkedIn:haracane
        url: https://www.linkedin.com/profile/view?id=205504421
      -
        title: キャッシュバック賃貸
        url: http://cbchintai.com
      -
        title: 賃貸情報株式会社
        url: http://chintaijyoho.co.jp
      -
        title: BuzzFinder
        url: https://www.nttcoms.com/service/buzzfinder/

  -
    title: 過去の発表
    type: dl
    links:
      -
        title: "\"見える\"Twitter全量リアルタイム解析 ～Hadoop/RabbitMQ処理の仕組みと可視化～"
        description:  Hadoop Conference Japan 2013 Winter＠東京ビッグサイト by 日本Hadoopユーザー会 [<a target="_blank" href="http://www.ustream.tv/recorded/28694028">Video</a>]
        url: https://speakerdeck.com/haracane/rabbitmqchu-li-falseshi-zu-mitoke-shi-hua
      -
        title: Hadoop＆RabbitMQを利用したTwitter全量リアルタイム解析
        description: Hadoopエンタープライズソリューションセミナー2012＠東京カンファレンスセンター品川 by NTTデータ
        url: https://speakerdeck.com/haracane/hadoopentapuraizusoriyusiyonsemina2012-hadoop-rabbitmqwoli-yong-sitatwitterquan-liang-riarutaimujie-xi
      -
        title: Large Scale Log Analysis for Marketing in NTT Communications
        description: Hadoop World 2011＠Sheraton NY by Cloudera
        url: http://www.slideshare.net/haracane/hadoop-world-2011-large-scale-log-data-analysis-for-marketing-in-ntt-communications-15528625
      -
        title: マーケティング向け大規模ログ解析事例紹介
        description: Hadoop Conference Japan 2011 Fall＠ベルサール汐留 by 日本Hadoopユーザー会 [<a target="_blank" href="http://www.ustream.tv/recorded/17518176">Video</a>]
        url: http://www.slideshare.net/haracane/hcj2011-fall0926

  -
    title: gem
    type: dl
    links:
      -
        title: bunnish
        description: お手軽RabbitMQ操作コマンド
        url: http://hatacomp.hateblo.jp/entry/release-bunnish-gem
      -
        title: priam
        description: Cassandra操作コマンド
        url: http://hatacomp.hateblo.jp/entry/release-priam-gem
      -
        title: apjson
        description: coolなjson表示コマンド
        url: http://hatacomp.hateblo.jp/entry/release-apjson-gem
      -
        title: okuyama
        description: OkuyamaのRubyクライアント
        url: https://github.com/haracane/okuyama
      -
        title: oauthtoken
        description: OAuth認証用トークン取得コマンド
        url: http://hatacomp.hateblo.jp/entry/2013/11/07/222716

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

gems:
  - jekyll-compass
