# Site settings
title: "江の島エンジニアBlog"
description: "湘南在住、渋谷で働くエンジニアのブログです"
baseurl: ""
url: "http://blog.enogineer.com"
twitter_username: haracane
github_username:  haracane

# Build settings
markdown: kramdown
permalink: pretty
