# Site settings
title: "江の島エンジニアBlog"
description: "湘南在住, 渋谷で働くエンジニアのブログです"
baseurl: ""
url: "http://blog.enogineer.com"
twitter_username: haracane
github_username:  haracane

tag_types:
-
  - "/genre/ruby/"
  - "Ruby"
-
  - "/genre/jekyll/"
  - "Jekyll"
-
  - "/genre/hadoop/"
  - "Hadoop"
-
  - "/genre/misc/"
  - "その他"

ruby_tags:
- Ruby

jekyll_tags:
- Jekyll

hadoop_tags:
- Hadoop

misc_tags:
- HTML5
- CSS
- スマホ
- Nginx

# Build settings
markdown: kramdown
permalink: pretty
