title: haracaneのブログ
author: haracane
description: >- # this means to ignore newlines until "baseurl:"
  プロダクト開発が好きなプログラマのブログです。
  RubyとTypeScriptによくお世話になっています。
  IDはharacane(はらけん)と読んでください。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://haracane.github.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Asia/Tokyo
google_analytics: G-Z370GDWX2B
twitter_username: haracane
# github_username:  haracane

permalink: /:year/:month/:day/:title/

# Build settings
theme: minima

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .gitignore
  - .tool-versions
  - .vscode
  - bin
  - lib
  - package-lock.json
  - package.json
  - tmp
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
