# Site settings
title: "江の島エンジニアBlog"
description: "湘南在住, 渋谷で働くエンジニアのブログです"
baseurl: ""
url: "http://blog.enogineer.com"
twitter_username: haracane
github_username:  haracane
google_analysis_id: UA-53664731-1
paginate: 1

default_genre: hadoop
tag_categories:
-
  - "/genre/hadoop/"
  - "Hadoop/Elasticsearch"
  -
    - Elasticsearch
    - Hadoop
-
  - "/genre/ruby/"
  - "Ruby"
  -
    - Ruby
    - Rails
-
  - "/genre/jekyll/"
  - "Jekyll"
  -
    - Jekyll
-
  - "/genre/misc/"
  - "その他"
  -
    - Git
    - HTML5
    - CSS
    - スマホ
    - Nginx

# Build settings
markdown: kramdown
permalink: pretty
