"/index.html":
  h1: "<a href=\"http://cbchintai.com\">キャッシュバック賃貸</a>でのRailsやElasticsearchなどを利用した開発事例を紹介をすることが多いです。"

"/categories.html":
  title: テーマ別連載記事の一覧
  description: "テーマ別連載記事の一覧です"
  h1: "テーマ別連載記事の一覧です"

"/genre/dp.html":
  title: DB/NoSQLなどデータ処理に関する記事
  description: "Hadoop、Elasticsearch、Redisなどデータ処理に関する記事の一覧です"
  h1: "DB、NoSQLなどデータ処理に関する記事の一覧です"

"/genre/ruby.html":
  title: "Ruby、Rails、RSpecなどの記事"
  description: "Ruby、Rails、RSpecなどの記事の一覧です"
  h1: "Ruby、Rails、RSpecなどの記事の一覧です"

"/genre/jekyll.html":
  title: "Jekyllに関する記事"
  description: "Jekyllでのブログ構築に関する記事の一覧です"
  h1: "Jekyllに関する記事の一覧です"

"/genre/misc.html":
  title: "Javascript,HTML5などに関する記事"
  description: "未分類のテーマの一覧です"
  h1: "未分類のテーマの一覧です"

"/backnumber.html":
  title: "バックナンバー"
  description: 過去に投稿した記事の一覧です
  h1: 過去に投稿した記事の一覧です
